language: rust
rust: nightly

before_install:
  - sudo apt-get update -qq
  - wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  - tar xzf LATEST.tar.gz
  - cd libsodium-* && ./configure && make && sudo make install
  - sudo apt-get install -y libsqlite3-dev

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
