language: rust
rust: nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libsqlite3-dev

script:
  - cargo build --verbose
  - cargo test --verbose
  - rustdoc --test README.md -L target
  - cargo doc
