[package]
authors = ["Johan Nielsen <sejr@google.com>"]
build = "build.rs"
name = "hat-backup"
version = "0.0.1-pre"

[[bin]]
name = "hat"
path = "src/hat/main.rs"

[build-dependencies]
capnpc = "*"
syntex = "*"

[dependencies]
capnp = "*"
clap = "*"
env_logger = "*"
error-type = "0.1.2"
libsodium-sys = "*"
log = "*"
quickcheck = "*"
rand = "*"
rustc-serialize = "*"
sodiumoxide = "*"
threadpool = "*"
time = "*"

[dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "0.6.*"

[build-dependencies.diesel_codegen]
default-features = false
features = ["with-syntex", "sqlite"]
version = "0.6.*"

[profile]

[profile.dev]
debug = true
opt-level = 0

[profile.release]
debug = false
opt-level = 2
