[package]
name = "hat-backup"
version = "0.0.1-pre"
authors = ["Johan Nielsen <sejr@google.com>"]

[[bin]]
name = "hat"
path = "src/hat/main.rs"

[dependencies]
rand = "*"
quickcheck = "0.2.19"
quickcheck_macros = "0.2.19"
clap = "*"
num = "0.1.24"
num-macros = "0.1.24"
rustc-serialize = "*"
time = "*"

sodiumoxide = "*"
threadpool = "*"

[dependencies.sqlite3]
git = "https://github.com/linuxfood/rustsqlite"


[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
debug = false
