[package]
name = "hat-backup"
version = "0.0.1-pre"
authors = ["Johan Nielsen <sejr@google.com>"]

[[bin]]
name = "hat"
path = "src/hat/main.rs"

[lib]
name = "hat-lib"
path = "src/hat/lib.rs"

[dependencies]
rand = "*"
quickcheck = "*"
quickcheck_macros = "*"

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide"

[dependencies.sqlite3]
git = "https://github.com/linuxfood/rustsqlite"


[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
debug = false
